bucket_name = "ganesh-iniyan-12"
region = "us-east-1"
environment = "dev"
cidr_block = "10.0.0.0/16"
subnet_cidr_block = "10.0.1.0/24"
frontend_repository_name = "ganesh-frontend-repo"
backend_repository_name = "ganesh-backend-repo"