name: ECR Push

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -var-file="dev.tfvars"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Backend
        run: |
          docker build -t backend ./docker-app/backend

          docker tag backend:latest \
            ${{ steps.login-ecr.outputs.registry }}/ganesh-backend-repo:${{ github.sha }}

          docker push \
            ${{ steps.login-ecr.outputs.registry }}/ganesh-backend-repo:${{ github.sha }}

      - name: Build Frontend
        run: |
          docker build -t frontend ./docker-app/frontend

          docker tag frontend:latest \
            ${{ steps.login-ecr.outputs.registry }}/ganesh-frontend-repo:${{ github.sha }}

          docker push \
            ${{ steps.login-ecr.outputs.registry }}/ganesh-frontend-repo:${{ github.sha }}