# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Check Node version
        run: node --version

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: |
          mkdir -p dist
          cp app.js dist/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-build
          path: dist/

  run:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-build
          path: dist

      - name: Verify artifact
        run: |
          ls -R dist

      - name: Run application
        run: |
          node dist/app.js
          sleep 5
          curl http://localhost:3000
          curl http://localhost:3000
